### PR TITLE
Add BFF

### PR DESCRIPTION
**Pull request by tunniclm**

### CODE REVIEW

**Comment by seabaylea** [comment]
Its a nit for now, but should BFFRoutes.swift be in `refresh/templates/basicweb/` or something with a more relevant naming like `refresh/templates/api/` ?

**Comment by seabaylea** [comment]
Note that we also need to host as swagger.yml that describes the API, etc so that the mobile SDK builders can use it.

**Comment by tunniclm** [comment]
Could add a `bff` directory instead and put it there, I probably should have created it that way to begin with.

**Comment by tunniclm** [comment]
Going to merge this and add serving swagger and cleanup in other PRs

**Comment by seabaylea** [comment]
@tunniclm @rfdickerson this still needs to have a hosted swagger spec that can be used for the mobile SDK generators.

**Comment by tunniclm** [comment]
@seabaylea Agreed. Swagger and route to serve it will come in next PR.

**Pull request merged**
