### PR TITLE
Release 4.8.2

### PR DESCRIPTION
**Pull request by SwiftDevOps**
Do NOT attempt to push further changes to this branch.

### CODE REVIEW

**Comment by EnriqueL8** [comment]
@christiancompton Why did we push directly to master? Don't we always push to develop then have a PR from develop to master?

**Comment by christiancompton** [comment]
@EnriqueL8 This was the PR into `develop` #466

**Comment by EnriqueL8** [comment]
okay, then why is this PR not develop to master? Sorry if I'm confused

**Comment by tunniclm** [comment]
@EnriqueL8 This looks fine. The prior "feature" PR was #466 and was merged (using a squash&merge) from a feature branch to develop (ie: `use`->`develop`). The PR we are commenting in here is a "release" PR #468 that was created automatically by devops when the original feature was merged.

It can be merged (using a normal merge) to make devops create and publish a release. It can be closed to ignore it and wait for a new feature to be merged when a new release PR will be raise. Or it can be left open (in which case it will be closed and replaced automatically with a new release PR if a new feature is merged into develop).

The process docs for the release and feature process are on the wiki: https://github.com/IBM-Swift/generator-swiftserver/wiki

**Comment by EnriqueL8** [comment]
Yes, I was not aware of that... @christiancompton explained it to me 😃

**Pull request merged**
