### PR TITLE
feat: updated mappings.json format and service generation

### PR DESCRIPTION
**Pull request by christiancompton**
BREAKING CHANGE: The mappings.json now contains the credential values in a 'credentials' object for each service, a major change from generator-ibm-service-enablement, which required updates to the CloudEnvironment library and other dependencies.

### CODE REVIEW

**Comment by christiancompton** [comment]
@EnriqueL8 @nhardman This will rev the major version of the generator.  Let's discuss if there are any other major changes we would like to include before publishing version 5.0.0, such as Kitura 2.3 and Swift 4.1 support.

**Comment by EnriqueL8** [comment]
Yes, now that Kitura 2.3 has been released we should make the changes before the major release along side `4.1`

**Comment by christiancompton** [comment]
@EnriqueL8 I have merged in the changes from `update_to_kitura23x`  in #520,  I have also upgraded to the latest `service-enablement` release, **1.1.7**.  This includes adding back support for Node 4, as well as the dependency changes.

**Comment by EnriqueL8** [comment]
@christiancompton One more thing I have realised, is that the `swift-version` file needs updating to `4.1`. I thought it was changed in the `update_to_kitura23x` branch.

**Comment by christiancompton** [comment]
Closes #507.

**Review by EnriqueL8 — APPROVED** [review]

**Pull request merged**
