### PR TITLE
feat: remove VSI support

### PR DESCRIPTION
**Pull request by youming-lin**

### CODE REVIEW

**Comment by christiancompton** [comment]
@djones6 @ianpartridge Are you alright with dropping VSI support for Swift applications?

**Comment by youming-lin** [comment]
@djones6 @ianpartridge Sorry for springing this on your guys, but we've already made a decision to stop supporting VSI as part of our work to leverage the existing DevOps templates instead of generating our own.

**Review by gee4vee — APPROVED** [review]
Looks good but let's let Ian or David respond before we continue.

**Review by ianpartridge — APPROVED** [review]

**Comment by youming-lin** [comment]
Currently blocked by: https://github.com/OpenKitten/NioDNS/issues/5

**Pull request merged**
