### PR TITLE
Fix bug with non-root docker user support

### PR DESCRIPTION
**Pull request by rolivieri**
Fix a bug with the logic added to `Dockerfile-tools` in https://github.com/IBM-Swift/generator-swiftserver/pull/227 where under some circumstances the docker user could not access tools in `/root` due to lacking access privileges.

### CODE REVIEW

**Comment by tunniclm** [comment]
Tested this out on a project created by `2.4.0` by updating the docker and cli files to match the changes above. Ran against a problem because the non-root user did not have permission to execute `swift`:

```
Building the project in the current directory started at Tue Jun 20 09:42:49 2017
FAILED                
Failed to build the project.

Dumping output from the command: 
Current folder: /swift-project
Command: build
Build configuration: release
Build folder: /swift-project/.build-ubuntu
Compiling the project...
Build configuration: release
/swift-utils/tools-utils.sh: line 52: swift: command not found
```

Looking inside the container, I see that `swift` is installed in `/root` which is not accessible:

```
$ which swift
/root/swift-3.1.1-RELEASE-ubuntu14.04/usr/bin/swift
$ ls -ld /root /root/swift-3.1.1-RELEASE-ubuntu14.04 /root/swift-3.1.1-RELEASE-ubuntu14.04/usr /root/swift-3.1.1-RELEASE-ubuntu14.04/usr/bin /root/swift-
3.1.1-RELEASE-ubuntu14.04/usr/bin/swift
drwx------ 5 root root     4096 May 24 17:35 /root
drwxr-xr-x 3 root root     4096 May 24 17:34 /root/swift-3.1.1-RELEASE-ubuntu14.04
drwxr-xr-x 8 root root     4096 Apr 21 22:07 /root/swift-3.1.1-RELEASE-ubuntu14.04/usr
drwxr-xr-x 2 root root     4096 Apr 21 22:07 /root/swift-3.1.1-RELEASE-ubuntu14.04/usr/bin
-rwxr-xr-x 1 root root 94309952 Apr 21 21:38 /root/swift-3.1.1-RELEASE-ubuntu14.04/usr/bin/swift
```

**Review by tunniclm — CHANGES_REQUESTED** [review]
Need to resolve the permission problem with the swift executable.

**Comment by rolivieri** [comment]
@tunniclm You may need to delete all of your docker images... what you are showing above does look outdated. It seems you are using an old version of the swift-ubuntu image and not the new one. The new one was tested and it can be used by a non-root user (plus the location of the swift binaries is also different).

**Comment by tunniclm** [comment]
@rolivieri Ah, I only deleted the top-level image, not the ubuntu one. I will try again.

**Comment by tunniclm** [comment]
@rolivieri Yes, that works fine now. Thanks.

**Review by tunniclm — APPROVED** [review]

**Pull request merged**
