### PR TITLE
chore(automate): automate the release flow

### PR DESCRIPTION
**Pull request by rob-deans**

### CODE REVIEW

**Comment by tunniclm** [comment]
Do we need to enforce that commits or PRs meet some criteria or template for them to be properly marked with their semantic version information for `standard-version`?

**Comment by rob-deans** [comment]
`feat:` will bump the minor but anything else will just bump the patch

If you do `feat`: There will be a subtitle in `CHANGES.md` called features

If you do `fix:` in the `CHANGES.md` it will have a subtitle called bug fixes

Any other commits would just be in the `CHANGES.md` but not under any headings

**Comment by rob-deans** [comment]
To bump the major version you need to have `BREAKING CHANGE:` but it cannot be on the first line in the commit message

**Comment by tunniclm** [comment]
Going to delay merging this until we have a compliant release -- we need to ensure that the features are correctly tagged so the version update and changelog update is right. For now, the commit linter has gone live which should prompt everyone to tag their features according to the new [Commit format documentation](https://github.com/IBM-Swift/generator-swiftserver/wiki/Commit-format-documentation).

**Review by tunniclm — APPROVED** [review]

**Pull request merged**
