### PR TITLE
feat: upgrading to Swift 4.2

### LINKED ISSUE #622: Generator should support Swift 4.2
Swift 4.2 was released in September, alongside Xcode 10.  The generator needs to be updated to produce projects that use Swift 4.2 by default.

### PR DESCRIPTION
**Pull request by christiancompton**
Closes #622.

### CODE REVIEW

**Comment by christiancompton** [comment]
I will plan to merge this in on 11/26 with https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/410

**Review by jkingoliver — APPROVED** [review]

**Comment by christiancompton** [comment]
This does depend on the Dockerfiles contained in https://github.com/ibm-developer/generator-ibm-cloud-enablement/pull/410

**Comment by djones6** [comment]
@christiancompton Should this now be `4.2.1` and `xcode10.1`?

**Comment by christiancompton** [comment]
@djones6 Since the 4.2.1 Buildpack is not out, this would result in a slow deployment for the Swift starterkits on IBM Cloud.  Once the buildpack has been deployed to production, then we can upgrade to 4.2.1.

**Comment by christiancompton** [comment]
My git config on my new machine was not configured properly - I am the author the the cloud-enablement upgrade commit.

**Pull request merged**
